name: Run Tests

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake test
      - name: Build gem
        run: gem build --strict --verbose *.gemspec
