pipelines:
  default:
    - step: &generate-sdks
        name: Generate SDKs
        image: timbru31/java-node:8-jdk-14
        caches:
          - node
        script:
          - npm install
          - npm run generate
        artifacts:
          - dist/**
    - parallel:
        - step: &run-php-tests
            name: Run PHP tests
            image: php:7.4
            caches:
              - composer
            script:
              - apt-get update && apt-get install -y unzip git
              - pecl install pcov && docker-php-ext-enable pcov
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - cd dist/sdk-php/
              - composer install
              - bash run-tests.sh
        - step: &run-python-tests
            name: Run Python tests
            image: python:3.9.1
            caches:
              - pip
            script:
              - pip install tox
              - cd dist/sdk-python/
              - tox
    - step: &check-versions
        name: Check SDK versions
        image: atlassian/default-image:2
        script:
          - npm run check-versions
  branches:
    master:
      - step: *generate-sdks
      - parallel:
          - step: *run-php-tests
          - step: *run-python-tests
      - step: *check-versions
      - step:
          name: Deploy to QA branch
          deployment: QA
          trigger: manual
          image: atlassian/default-image:2
          script:
            - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
            - git fetch && git checkout qa
            - git reset --hard master
            - git push --force origin qa
    qa:
      - step: *generate-sdks
      - parallel:
          - step: *run-php-tests
          - step: *run-python-tests
      - step: *check-versions
      - step:
          name: Deploy to GitHub
          deployment: GitHub
          trigger: manual
          image: atlassian/default-image:2
          script:
            - 'false'
