pipelines:
  default:
    - step: &generate-sdks
        name: Generate SDKs
        image: timbru31/java-node:8-jdk-14
        caches:
          - node
        script:
          - npm install
          - npm run generate
        artifacts:
          - dist/**
    - parallel:
        - step: &run-php-tests
            name: Run PHP tests
            image: php:7.4
            caches:
              - composer
            script:
              - apt-get update && apt-get install -y unzip git
              - pecl install pcov && docker-php-ext-enable pcov
              - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
              - cd dist/sdk-php/
              - composer install
              - bash run-tests.sh
        - step: &run-python-tests
            name: Run Python tests
            image: python:3.9.1
            caches:
              - pip
            script:
              - pip install tox
              - cd dist/sdk-python/
              - tox
        - step: &run-java-tests
            name: Run Java tests
            image: maven:3.6.3-jdk-8
            caches:
              - maven
            script:
              - cd dist/sdk-java/
              - mvn -B test
  branches:
    master:
      - step: *generate-sdks
      - parallel:
          - step: *run-php-tests
          - step: *run-python-tests
          - step: *run-java-tests
      - step:
          name: Deploy to QA Branch
          deployment: QA Branch
          trigger: manual
          image: atlassian/default-image:2
          script:
            - git push origin master:qa
    qa:
      - step: *generate-sdks
      - parallel:
          - step: *run-php-tests
          - step: *run-python-tests
          - step: *run-java-tests
      - step:
          name: Deploy to SDK Repos
          deployment: SDK Repos
          trigger: manual
          image: atlassian/default-image:2
          script:
            - bash scripts/deploy-sdk-repos.sh
      - step:
          name: Deploy to GitHub Repo
          deployment: GitHub Repo
          trigger: manual
          image: atlassian/default-image:2
          script:
            - git push https://$GITHUB_TOKEN@github.com/Trulioo/OpenAPI qa:master
