inputSpec: developer.yaml
gitUserId: Trulioo
globalProperties:
  apiTests: false
  modelTests: false
sampleApp:
  indexTemplateFile: sample-apps/common/index.html.mustache
  idvSteps:
    testAuthentication:
      index: 1
      longName: Test Authentication
      shortName: Authentication
      description: |-
        You can use this function to check whether your API key is working. The only thing that you need to provide is a
        mode: "trial" or "live".
      buttonElementId: test-authentication
      responseElementId: test-authentication-response
    getCountries:
      index: 2
      longName: Get Country Codes
      shortName: Countries
      description: |-
        Trulioo's API is structured to make calls by country. If you are not sure what countries are configured for your
        account, Trulioo provides this function to retrieve this information at any time. Simply run the following to
        receive the full list of country codes available for your account.
      buttonElementId: get-countries
      responseElementId: get-countries-response
    getTestEntities:
      index: 3
      longName: Get Test Entities
      shortName: Test Entities
      description: |-
        Now that you know what country codes are valid for your account, you can see what test entities exist for each
        of these countries.
        <br>
        These test entities can be used to test identity verification in step 5. They only serve as demo data, and
        different ones exist for every country.
      buttonElementId: get-test-entities
      responseElementId: get-test-entities-response
    getConsents:
      index: 4
      longName: Get Consents
      shortName: Consents
      description: |-
        It is the responsibility of the developer to ensure that any necessary consents are being collected from the
        individual being verified. See
        <a href="https://gateway-admin.trulioo.com/termsandconditions" target="_blank" rel="noreferrer">
          Trulioo's Terms and Conditions</a>.
        <br><br>
        Due to the nature of some of our data sources, you may need to obtain consent from your customer for their data
        to be sent to a particular source. You may or may not be configured to use any of these data sources, so it is
        recommended to run this function for all of the countries obtained in step 2. This will give you a list of data
        sources that require additional consents in each country. If applicable, you can obtain these special consents
        from your customer, and then provide them in the Consent For Data Sources property of the verify request.
      buttonElementId: get-consents
      responseElementId: get-consents-response
    verify:
      index: 5
      longName: Verify
      shortName: Verify
      description: |-
        Once steps 1 through 4 have been completed, you should have everything needed to carry out an identity
        verification request. Using one of the country codes from step 2, one of the test entities from step 3, and any
        necessary consents from step 4, you can now run the following.
      additionalFieldsDescription: |-
        Accept Trulioo Terms and Conditions (boolean): This flag indicates that you accept Trulioo's Terms and
        Conditions. The verification request will be executed only if the value of this property is passed as true.
        <br><br>
        Cleansed Address (boolean): Trulioo provides a service to check and ensure that the address data is correct and
        that all necessary address fields have been provided. In general, these cleansed addresses have a higher
        likelihood of producing a match result. Set this property to true to receive address cleanse information.
        <br><br>
        Configuration Name (string): When verifying an identity, this should be set to "Identity Verification".
      buttonElementId: verify
      responseElementId: verify-response
