name: Run Tests

on: [workflow_dispatch, push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: pcov
      - name: Install PHP dependencies
        run: composer install
      - name: Run tests
        run: bash run-tests.sh
