/**
 * Trulioo SDK
 * Trulioo SDK 
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PersonInfoAdditionalFields model module.
 * @module model/PersonInfoAdditionalFields
 * @version 1.4
 */
class PersonInfoAdditionalFields {
    /**
     * Constructs a new <code>PersonInfoAdditionalFields</code>.
     * @alias module:model/PersonInfoAdditionalFields
     */
    constructor() { 
        
        PersonInfoAdditionalFields.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PersonInfoAdditionalFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PersonInfoAdditionalFields} obj Optional instance to populate.
     * @return {module:model/PersonInfoAdditionalFields} The populated <code>PersonInfoAdditionalFields</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PersonInfoAdditionalFields();

            if (data.hasOwnProperty('FullName')) {
                obj['FullName'] = ApiClient.convertToType(data['FullName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Full name of the individual to be verified.
 * @member {String} FullName
 */
PersonInfoAdditionalFields.prototype['FullName'] = undefined;






export default PersonInfoAdditionalFields;

