<?php

/**
 * Trulioo PHP SDK
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;
use OpenAPI\Client\Model\AppendedField;

class AppendedFieldTest extends TestCase
{
    private AppendedField $appendedField;

    public function setUp(): void
    {
        $this->appendedField = new AppendedField([]);
    }

    public function testPropertyFieldName()
    {
        $this->appendedField->setFieldName('first_name');
        $this->assertEquals('first_name', $this->appendedField->getFieldName());
    }

    public function testPropertyData()
    {
        $this->appendedField->setData('abc');
        $this->assertEquals('abc', $this->appendedField->getData());
    }
}
