<?php

/**
 * Trulioo PHP SDK
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;
use OpenAPI\Client\Model\BusinessSearchResponseIndustryCode;

class BusinessSearchResponseIndustryCodeTest extends TestCase
{
    private BusinessSearchResponseIndustryCode $businessSearchResponseIndustryCode;

    public function setUp(): void
    {
        $this->businessSearchResponseIndustryCode = new BusinessSearchResponseIndustryCode([]);
    }

    public function testPropertyCode()
    {
        $this->businessSearchResponseIndustryCode->setCode('abc');
        $this->assertEquals('abc', $this->businessSearchResponseIndustryCode->getCode());
    }

    public function testPropertyDescription()
    {
        $this->businessSearchResponseIndustryCode->setDescription('desc');
        $this->assertEquals('desc', $this->businessSearchResponseIndustryCode->getDescription());
    }
}
