<?php

/**
 * Trulioo PHP SDK
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;
use OpenAPI\Client\Model\Consent;

class ConsentTest extends TestCase
{
    private Consent $consent;

    public function setUp(): void
    {
        $this->consent = new Consent([]);
    }

    public function testPropertyName()
    {
        $this->consent->setName('Credit Agency');
        $this->assertEquals('Credit Agency', $this->consent->getName());
    }

    public function testPropertyText()
    {
        $this->consent->setText('A credit agency');
        $this->assertEquals('A credit agency', $this->consent->getText());
    }

    public function testPropertyUrl()
    {
        $this->consent->setUrl('https://trulioo.com');
        $this->assertEquals('https://trulioo.com', $this->consent->getUrl());
    }
}
