<?php

/**
 * Trulioo PHP SDK
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;
use OpenAPI\Client\Model\LocationAdditionalFields;

class LocationAdditionalFieldsTest extends TestCase
{
    private LocationAdditionalFields $locationAdditionalFields;

    public function setUp(): void
    {
        $this->locationAdditionalFields = new LocationAdditionalFields([]);
    }

    public function testPropertyAddress1()
    {
        $this->locationAdditionalFields->setAddress1('123 Seasame St');
        $this->assertEquals('123 Seasame St', $this->locationAdditionalFields->getAddress1());
    }
}
