<?php

/**
 * Trulioo PHP SDK
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;
use OpenAPI\Client\Model\PersonInfoAdditionalFields;

class PersonInfoAdditionalFieldsTest extends TestCase
{
    private PersonInfoAdditionalFields $personInfoAdditionalFields;

    public function setUp(): void
    {
        $this->personInfoAdditionalFields = new PersonInfoAdditionalFields([]);
    }

    public function testPropertyFullName()
    {
        $this->personInfoAdditionalFields->setFullName('A B C');
        $this->assertEquals('A B C', $this->personInfoAdditionalFields->getFullName());
    }
}
