<?php

/**
 * Trulioo PHP SDK
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;
use OpenAPI\Client\Model\RecordRule;

class RecordRuleTest extends TestCase
{
    private RecordRule $recordRule;

    public function setUp(): void
    {
        $this->recordRule = new RecordRule([]);
    }

    public function testPropertyRuleName()
    {
        $this->recordRule->setRuleName('rule1');
        $this->assertEquals('rule1', $this->recordRule->getRuleName());
    }

    public function testPropertyNote()
    {
        $this->recordRule->setNote('test');
        $this->assertEquals('test', $this->recordRule->getNote());
    }
}
