<?php

/**
 * Trulioo PHP SDK
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;
use OpenAPI\Client\Model\ServiceError;

class ServiceErrorTest extends TestCase
{
    private ServiceError $serviceError;

    public function setUp(): void
    {
        $this->serviceError = new ServiceError([]);
    }

    public function testPropertyCode()
    {
        $this->serviceError->setCode('2319');
        $this->assertEquals('2319', $this->serviceError->getCode());
    }

    public function testPropertyMessage()
    {
        $this->serviceError->setMessage('test');
        $this->assertEquals('test', $this->serviceError->getMessage());
    }
}
