<?php

/**
 * Trulioo PHP SDK
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;
use OpenAPI\Client\Model\TransactionRecordResultAllOf;
use OpenAPI\Client\Model\DataField;

class TransactionRecordResultAllOfTest extends TestCase
{
    private TransactionRecordResultAllOf $transactionRecordResultAllOf;

    public function setUp(): void
    {
        $this->transactionRecordResultAllOf = new TransactionRecordResultAllOf([]);
    }

    public function testPropertyInputFields()
    {
        $this->transactionRecordResultAllOf->setInputFields([
            new DataField([
                'field_name' => 'field',
                'value' => 'test'
            ])
        ]);
        $this->assertEquals(
            [
                new DataField([
                    'field_name' => 'field',
                    'value' => 'test'
                ])
            ],
            $this->transactionRecordResultAllOf->getInputFields()
        );
    }
}
