=begin
Trulioo Ruby SDK

Gem version: 1.0.0
Trulioo OpenAPI version: v1
Generated by OpenAPI Generator version: 5.0.1
=end

require "spec_helper"
require "securerandom"

describe Trulioo::Document do
  let(:model) { Trulioo::Document.new }
  let(:test_attributes) {
    {
      document_front_image: "base64",
      document_back_image: "base64",
      live_photo: "base64",
      document_type: SecureRandom.alphanumeric(10),
      accept_incomplete_document: true,
      validate_document_image_quality: true,
    }
  }

  it "should have correct array of acceptable JSON keys" do
    expect(Trulioo::Document.acceptable_attributes).to eql([
      :"DocumentFrontImage",
      :"DocumentBackImage",
      :"LivePhoto",
      :"DocumentType",
      :"AcceptIncompleteDocument",
      :"ValidateDocumentImageQuality",
    ])
  end

  it "should have correct array of acceptable attribute types" do
    expect(Trulioo::Document.openapi_types.values).to eql([
      :"String",
      :"String",
      :"String",
      :"String",
      :"Boolean",
      :"Boolean",
    ])
  end

  it "should have correct set of nullable attributes" do
    expect(Trulioo::Document.openapi_nullable).to eql(Set.new([]))
  end

  it "should have correct array of invalid properties" do
    expected_invalid_properties = Array.new

    expect(model.list_invalid_properties).to eql(expected_invalid_properties)
  end

  it "should perform any validation in custom attribute writers" do
  end

  it "should correctly initialize with attributes from Hash" do
    model = Trulioo::Document.new(test_attributes)

    expect(model.document_front_image).to be(test_attributes[:document_front_image])
    expect(model.document_back_image).to be(test_attributes[:document_back_image])
    expect(model.live_photo).to be(test_attributes[:live_photo])
    expect(model.document_type).to be(test_attributes[:document_type])
    expect(model.accept_incomplete_document).to be(test_attributes[:accept_incomplete_document])
    expect(model.validate_document_image_quality).to be(test_attributes[:validate_document_image_quality])

    expect(model.valid?).to be true
  end

  it "should not initialize with a non-Hash argument" do
    expect { Trulioo::Document.new([]) }.to raise_error(ArgumentError)
  end

  it "should not initialize with a Hash that contains an invalid attribute" do
    expect { Trulioo::Document.new({ test_invalid_key: "" }) }.to raise_error(ArgumentError)
  end

  it "should correctly check object equality" do
    model.document_front_image = test_attributes[:document_front_image]

    expect(model).to equal(model)
    expect(model).to eql(Trulioo::Document.new({ document_front_image: test_attributes[:document_front_image] }))
  end

  it "should correctly calculate hash code" do
    model.document_front_image = test_attributes[:document_front_image]

    expect(Trulioo::Document.new({ document_front_image: test_attributes[:document_front_image] }).hash).to eql(model.hash)
  end
end
