=begin
Trulioo Ruby SDK

Gem version: 1.0.0
Trulioo OpenAPI version: v1
Generated by OpenAPI Generator version: 5.0.1
=end

require "spec_helper"
require "securerandom"

describe Trulioo::RecordRule do
  let(:model) { Trulioo::RecordRule.new }
  let(:test_attributes) {
    {
      rule_name: SecureRandom.alphanumeric(10),
      note: SecureRandom.alphanumeric(10),
    }
  }

  it "should have correct array of acceptable JSON keys" do
    expect(Trulioo::RecordRule.acceptable_attributes).to eql([
      :"RuleName",
      :"Note",
    ])
  end

  it "should have correct array of acceptable attribute types" do
    expect(Trulioo::RecordRule.openapi_types.values).to eql([
      :"String",
      :"String",
    ])
  end

  it "should have correct set of nullable attributes" do
    expect(Trulioo::RecordRule.openapi_nullable).to eql(Set.new([]))
  end

  it "should have correct array of invalid properties" do
    expected_invalid_properties = Array.new

    expect(model.list_invalid_properties).to eql(expected_invalid_properties)
  end

  it "should perform any validation in custom attribute writers" do
  end

  it "should correctly initialize with attributes from Hash" do
    model = Trulioo::RecordRule.new(test_attributes)

    expect(model.rule_name).to be(test_attributes[:rule_name])
    expect(model.note).to be(test_attributes[:note])

    expect(model.valid?).to be true
  end

  it "should not initialize with a non-Hash argument" do
    expect { Trulioo::RecordRule.new([]) }.to raise_error(ArgumentError)
  end

  it "should not initialize with a Hash that contains an invalid attribute" do
    expect { Trulioo::RecordRule.new({ test_invalid_key: "" }) }.to raise_error(ArgumentError)
  end

  it "should correctly check object equality" do
    model.rule_name = test_attributes[:rule_name]

    expect(model).to equal(model)
    expect(model).to eql(Trulioo::RecordRule.new({ rule_name: test_attributes[:rule_name] }))
  end

  it "should correctly calculate hash code" do
    model.rule_name = test_attributes[:rule_name]

    expect(Trulioo::RecordRule.new({ rule_name: test_attributes[:rule_name] }).hash).to eql(model.hash)
  end
end
