=begin
Trulioo Ruby SDK

Gem version: 1.0.0
Trulioo OpenAPI version: v1
Generated by OpenAPI Generator version: 5.0.1
=end

require "spec_helper"
require "securerandom"

describe Trulioo::Consent do
  let(:model) { Trulioo::Consent.new }
  let(:test_attributes) {
    {
      name: SecureRandom.alphanumeric(10),
      text: SecureRandom.alphanumeric(10),
      url: SecureRandom.alphanumeric(10),
    }
  }

  it "should have correct array of acceptable JSON keys" do
    expect(Trulioo::Consent.acceptable_attributes).to eql([
      :"Name",
      :"Text",
      :"Url",
    ])
  end

  it "should have correct array of acceptable attribute types" do
    expect(Trulioo::Consent.openapi_types.values).to eql([
      :"String",
      :"String",
      :"String",
    ])
  end

  it "should have correct set of nullable attributes" do
    expect(Trulioo::Consent.openapi_nullable).to eql(Set.new([]))
  end

  it "should have correct array of invalid properties" do
    expected_invalid_properties = Array.new

    expect(model.list_invalid_properties).to eql(expected_invalid_properties)
  end

  it "should perform any validation in custom attribute writers" do
  end

  it "should correctly initialize with attributes from Hash" do
    model = Trulioo::Consent.new(test_attributes)

    expect(model.name).to be(test_attributes[:name])
    expect(model.text).to be(test_attributes[:text])
    expect(model.url).to be(test_attributes[:url])

    expect(model.valid?).to be true
  end

  it "should not initialize with a non-Hash argument" do
    expect { Trulioo::Consent.new([]) }.to raise_error(ArgumentError)
  end

  it "should not initialize with a Hash that contains an invalid attribute" do
    expect { Trulioo::Consent.new({ test_invalid_key: "" }) }.to raise_error(ArgumentError)
  end

  it "should correctly check object equality" do
    model.name = test_attributes[:name]

    expect(model).to equal(model)
    expect(model).to eql(Trulioo::Consent.new({ name: test_attributes[:name] }))
  end

  it "should correctly calculate hash code" do
    model.name = test_attributes[:name]

    expect(Trulioo::Consent.new({ name: test_attributes[:name] }).hash).to eql(model.hash)
  end
end
