=begin
Trulioo Ruby SDK

Gem version: 1.0.0
Trulioo OpenAPI version: v1
Generated by OpenAPI Generator version: 5.0.1
=end

require "spec_helper"
require "securerandom"

describe Trulioo::LocationAdditionalFields do
  let(:model) { Trulioo::LocationAdditionalFields.new }
  let(:test_attributes) {
    {
      address1: SecureRandom.alphanumeric(10),
    }
  }

  it "should have correct array of acceptable JSON keys" do
    expect(Trulioo::LocationAdditionalFields.acceptable_attributes).to eql([
      :"Address1",
    ])
  end

  it "should have correct array of acceptable attribute types" do
    expect(Trulioo::LocationAdditionalFields.openapi_types.values).to eql([
      :"String",
    ])
  end

  it "should have correct set of nullable attributes" do
    expect(Trulioo::LocationAdditionalFields.openapi_nullable).to eql(Set.new([]))
  end

  it "should have correct array of invalid properties" do
    expected_invalid_properties = Array.new

    expect(model.list_invalid_properties).to eql(expected_invalid_properties)
  end

  it "should perform any validation in custom attribute writers" do
  end

  it "should correctly initialize with attributes from Hash" do
    model = Trulioo::LocationAdditionalFields.new(test_attributes)

    expect(model.address1).to be(test_attributes[:address1])

    expect(model.valid?).to be true
  end

  it "should not initialize with a non-Hash argument" do
    expect { Trulioo::LocationAdditionalFields.new([]) }.to raise_error(ArgumentError)
  end

  it "should not initialize with a Hash that contains an invalid attribute" do
    expect { Trulioo::LocationAdditionalFields.new({ test_invalid_key: "" }) }.to raise_error(ArgumentError)
  end

  it "should correctly check object equality" do
    model.address1 = test_attributes[:address1]

    expect(model).to equal(model)
    expect(model).to eql(Trulioo::LocationAdditionalFields.new({ address1: test_attributes[:address1] }))
  end

  it "should correctly calculate hash code" do
    model.address1 = test_attributes[:address1]

    expect(Trulioo::LocationAdditionalFields.new({ address1: test_attributes[:address1] }).hash).to eql(model.hash)
  end
end
