=begin
Trulioo Ruby SDK

Gem version: 1.0.0
Trulioo OpenAPI version: v1
Generated by OpenAPI Generator version: 5.0.1
=end

require "spec_helper"
require "securerandom"

describe Trulioo::NationalId do
  let(:model) { Trulioo::NationalId.new }
  let(:test_attributes) {
    {
      number: SecureRandom.alphanumeric(10),
      type: SecureRandom.alphanumeric(10),
      district_of_issue: SecureRandom.alphanumeric(10),
      city_of_issue: SecureRandom.alphanumeric(10),
      province_of_issue: SecureRandom.alphanumeric(10),
      county_of_issue: SecureRandom.alphanumeric(10),
    }
  }

  it "should have correct array of acceptable JSON keys" do
    expect(Trulioo::NationalId.acceptable_attributes).to eql([
      :"Number",
      :"Type",
      :"DistrictOfIssue",
      :"CityOfIssue",
      :"ProvinceOfIssue",
      :"CountyOfIssue",
    ])
  end

  it "should have correct array of acceptable attribute types" do
    expect(Trulioo::NationalId.openapi_types.values).to eql([
      :"String",
      :"String",
      :"String",
      :"String",
      :"String",
      :"String",
    ])
  end

  it "should have correct set of nullable attributes" do
    expect(Trulioo::NationalId.openapi_nullable).to eql(Set.new([]))
  end

  it "should have correct array of invalid properties" do
    expected_invalid_properties = Array.new

    expect(model.list_invalid_properties).to eql(expected_invalid_properties)
  end

  it "should perform any validation in custom attribute writers" do
  end

  it "should correctly initialize with attributes from Hash" do
    model = Trulioo::NationalId.new(test_attributes)

    expect(model.number).to be(test_attributes[:number])
    expect(model.type).to be(test_attributes[:type])
    expect(model.district_of_issue).to be(test_attributes[:district_of_issue])
    expect(model.city_of_issue).to be(test_attributes[:city_of_issue])
    expect(model.province_of_issue).to be(test_attributes[:province_of_issue])
    expect(model.county_of_issue).to be(test_attributes[:county_of_issue])

    expect(model.valid?).to be true
  end

  it "should not initialize with a non-Hash argument" do
    expect { Trulioo::NationalId.new([]) }.to raise_error(ArgumentError)
  end

  it "should not initialize with a Hash that contains an invalid attribute" do
    expect { Trulioo::NationalId.new({ test_invalid_key: "" }) }.to raise_error(ArgumentError)
  end

  it "should correctly check object equality" do
    model.number = test_attributes[:number]

    expect(model).to equal(model)
    expect(model).to eql(Trulioo::NationalId.new({ number: test_attributes[:number] }))
  end

  it "should correctly calculate hash code" do
    model.number = test_attributes[:number]

    expect(Trulioo::NationalId.new({ number: test_attributes[:number] }).hash).to eql(model.hash)
  end
end
