=begin
Trulioo Ruby SDK

Gem version: 1.0.0
Trulioo OpenAPI version: v1
Generated by OpenAPI Generator version: 5.0.1
=end

require "spec_helper"
require "securerandom"

describe Trulioo::NormalizedDatasourceField do
  let(:model) { Trulioo::NormalizedDatasourceField.new }
  let(:test_attributes) {
    {
      field_name: SecureRandom.alphanumeric(64),
      type: SecureRandom.alphanumeric(250),
    }
  }

  it "should have correct array of acceptable JSON keys" do
    expect(Trulioo::NormalizedDatasourceField.acceptable_attributes).to eql([
      :"FieldName",
      :"Type",
    ])
  end

  it "should have correct array of acceptable attribute types" do
    expect(Trulioo::NormalizedDatasourceField.openapi_types.values).to eql([
      :"String",
      :"String",
    ])
  end

  it "should have correct set of nullable attributes" do
    expect(Trulioo::NormalizedDatasourceField.openapi_nullable).to eql(Set.new([]))
  end

  it "should have correct array of invalid properties" do
    expected_invalid_properties = Array.new

    model.instance_variable_set(:@field_name, SecureRandom.alphanumeric(64 + 1))
    expected_invalid_properties.push('invalid value for "field_name", the character length must be smaller than or equal to 64.')

    model.instance_variable_set(:@type, SecureRandom.alphanumeric(250 + 1))
    expected_invalid_properties.push('invalid value for "type", the character length must be smaller than or equal to 250.')

    expect(model.list_invalid_properties).to eql(expected_invalid_properties)
  end

  it "should perform any validation in custom attribute writers" do
    expect { model.field_name = SecureRandom.alphanumeric(64 + 1) }.to raise_error(ArgumentError)
    expect { model.type = SecureRandom.alphanumeric(250 + 1) }.to raise_error(ArgumentError)
  end

  it "should correctly initialize with attributes from Hash" do
    model = Trulioo::NormalizedDatasourceField.new(test_attributes)

    expect(model.field_name).to be(test_attributes[:field_name])
    expect(model.type).to be(test_attributes[:type])

    expect(model.valid?).to be true
  end

  it "should not initialize with a non-Hash argument" do
    expect { Trulioo::NormalizedDatasourceField.new([]) }.to raise_error(ArgumentError)
  end

  it "should not initialize with a Hash that contains an invalid attribute" do
    expect { Trulioo::NormalizedDatasourceField.new({ test_invalid_key: "" }) }.to raise_error(ArgumentError)
  end

  it "should correctly check object equality" do
    model.field_name = test_attributes[:field_name]

    expect(model).to equal(model)
    expect(model).to eql(Trulioo::NormalizedDatasourceField.new({ field_name: test_attributes[:field_name] }))
  end

  it "should correctly calculate hash code" do
    model.field_name = test_attributes[:field_name]

    expect(Trulioo::NormalizedDatasourceField.new({ field_name: test_attributes[:field_name] }).hash).to eql(model.hash)
  end
end
