=begin
Trulioo Ruby SDK

Gem version: 1.0.0
Trulioo OpenAPI version: v1
Generated by OpenAPI Generator version: 5.0.1
=end

require "spec_helper"
require "securerandom"

describe Trulioo::ServiceError do
  let(:model) { Trulioo::ServiceError.new }
  let(:test_attributes) {
    {
      code: SecureRandom.alphanumeric(10),
      message: SecureRandom.alphanumeric(10),
    }
  }

  it "should have correct array of acceptable JSON keys" do
    expect(Trulioo::ServiceError.acceptable_attributes).to eql([
      :"Code",
      :"Message",
    ])
  end

  it "should have correct array of acceptable attribute types" do
    expect(Trulioo::ServiceError.openapi_types.values).to eql([
      :"String",
      :"String",
    ])
  end

  it "should have correct set of nullable attributes" do
    expect(Trulioo::ServiceError.openapi_nullable).to eql(Set.new([]))
  end

  it "should have correct array of invalid properties" do
    expected_invalid_properties = Array.new

    expect(model.list_invalid_properties).to eql(expected_invalid_properties)
  end

  it "should perform any validation in custom attribute writers" do
  end

  it "should correctly initialize with attributes from Hash" do
    model = Trulioo::ServiceError.new(test_attributes)

    expect(model.code).to be(test_attributes[:code])
    expect(model.message).to be(test_attributes[:message])

    expect(model.valid?).to be true
  end

  it "should not initialize with a non-Hash argument" do
    expect { Trulioo::ServiceError.new([]) }.to raise_error(ArgumentError)
  end

  it "should not initialize with a Hash that contains an invalid attribute" do
    expect { Trulioo::ServiceError.new({ test_invalid_key: "" }) }.to raise_error(ArgumentError)
  end

  it "should correctly check object equality" do
    model.code = test_attributes[:code]

    expect(model).to equal(model)
    expect(model).to eql(Trulioo::ServiceError.new({ code: test_attributes[:code] }))
  end

  it "should correctly calculate hash code" do
    model.code = test_attributes[:code]

    expect(Trulioo::ServiceError.new({ code: test_attributes[:code] }).hash).to eql(model.hash)
  end
end
