'!include': ./shared/common.yaml

artifactVersion: 1.0.1
generatorName: php
packageName: trulioo/trulioo-sdk
projectDescription: Trulioo PHP SDK
licenseName: Apache-2.0
gitRepoId: sdk-php
outputDir: ./dist/sdk-php/
templateDir: ./templates/php/
ignoreFileOverride: ./configs/openapi-generator-ignore/php.openapi-generator-ignore
files:
  .gitattributes: {}
  run-tests.sh: {}
