'!include': ./shared/common.yaml

artifactVersion: 1.0.2
generatorName: python
packageName: trulioo_sdk
projectDescription: Trulioo Python SDK
licenseName: Apache-2.0
gitRepoId: sdk-python
outputDir: ./dist/sdk-python/
templateDir: ./templates/python/
ignoreFileOverride: ./configs/openapi-generator-ignore/python.openapi-generator-ignore
