'!include': ./shared/common.yaml

packageName: trulioo_sdk
projectDescription: Trulioo Python SDK
licenseName: Apache-2.0
gitRepoId: sdk-python
artifactVersion: 1.0.0
generatorName: python
outputDir: ./dist/sdk-python/
templateDir: ./templates/python/
ignoreFileOverride: ./configs/openapi-generator-ignore/python.openapi-generator-ignore
