/**
 * Trulioo SDK
 * Trulioo SDK 
 *
 * The version of the OpenAPI document: 1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TruliooSdk);
  }
}(this, function(expect, TruliooSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TruliooSdk.DriverLicence();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DriverLicence', function() {
    it('should create an instance of DriverLicence', function() {
      // uncomment below and update the code to test DriverLicence
      //var instane = new TruliooSdk.DriverLicence();
      //expect(instance).to.be.a(TruliooSdk.DriverLicence);
    });

    it('should have the property _number (base name: "Number")', function() {
      // uncomment below and update the code to test the property _number
      //var instane = new TruliooSdk.DriverLicence();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "State")', function() {
      // uncomment below and update the code to test the property state
      //var instane = new TruliooSdk.DriverLicence();
      //expect(instance).to.be();
    });

    it('should have the property dayOfExpiry (base name: "DayOfExpiry")', function() {
      // uncomment below and update the code to test the property dayOfExpiry
      //var instane = new TruliooSdk.DriverLicence();
      //expect(instance).to.be();
    });

    it('should have the property monthOfExpiry (base name: "MonthOfExpiry")', function() {
      // uncomment below and update the code to test the property monthOfExpiry
      //var instane = new TruliooSdk.DriverLicence();
      //expect(instance).to.be();
    });

    it('should have the property yearOfExpiry (base name: "YearOfExpiry")', function() {
      // uncomment below and update the code to test the property yearOfExpiry
      //var instane = new TruliooSdk.DriverLicence();
      //expect(instance).to.be();
    });

  });

}));
