=begin
Trulioo Ruby SDK

Gem version: 1.0.0
Trulioo OpenAPI version: v1
Generated by OpenAPI Generator version: 5.0.1
=end

require "spec_helper"
require "webmock/rspec"

describe Trulioo::CommonApi do
  let(:api) {
    configuration = Trulioo::Configuration.new
    configuration.api_key["ApiKeyAuth"] = "test-api-key"
    configuration.debugging = true
    api_client = Trulioo::ApiClient.new(configuration)
    Trulioo::CommonApi.new(api_client)
  }

  describe "#common_ip_info" do
    context "when receiving 200 success" do
      before(:each) do
        stub_request(:any, /.*/).to_return(status: 200, body: '{
          "IP": "0.0.0.0"
        }')
      end
      let!(:result) {
        api.common_ip_info("trial")
      }

      it "should correctly call the API" do
        expect(
          a_request(:get, "https://gateway.trulioo.com/trial/common/v1/ip-info")
        ).to have_been_made
      end

      it "should correctly deserialize the response" do
        expect(result).to eql({
          IP: "0.0.0.0",
        })
      end
    end

    context "when receiving 401 unauthorized" do
      before(:each) do
        stub_request(:any, /.*/).to_return(status: 401)
      end

      it "should throw an ApiError" do
        expect {
          api.common_ip_info("trial")
        }.to raise_error(Trulioo::ApiError, /HTTP status code: 401/)
      end
    end

    context "with parameter 'mode' as nil" do
      it "should throw an ArgumentError" do
        expect { api.common_ip_info(nil) }.to raise_error(
          ArgumentError,
          "Missing the required parameter 'mode' when calling CommonApi.common_ip_info"
        )
      end
    end
  end
end
