name: Run Tests

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Run tests
        run: dotnet test src/Trulioo.SDK.Test/
