name: Create Pull Requests

on:
  push:
    branches: [master]

jobs:
  generate-sdks:
    name: Generate SDKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node dependencies
        run: npm install
      - name: Check SDK versions
        run: npm run check-versions
      - name: Generate SDKs
        run: npm run generate
      - name: Save generated SDKs
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*
  create-pull-requests:
    name: Create pull requests
    needs: generate-sdks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk-repo: ['sdk-php', 'sdk-python']
    steps:
      - name: Retrieve generated SDKs
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Get master branch of target SDK repo
        uses: actions/checkout@v2
        with:
          repository: Trulioo/${{ matrix.sdk-repo }}
          token: ${{ secrets.LANGUAGE_REPO_TOKEN }}
          path: current/${{ matrix.sdk-repo }}
      - name: Update code
        run: rsync -a --delete --exclude=.git/ dist/${{ matrix.sdk-repo }}/ current/${{ matrix.sdk-repo }}/
      - name: Create pull request in target SDK repo
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.LANGUAGE_REPO_TOKEN }}
          path: current/${{ matrix.sdk-repo }}
          branch: sdk-update
          branch-suffix: timestamp
          commit-message: Automated update
          title: Automated update
          body: ''
