name: Run Tests

on: [workflow_dispatch, push]

jobs:
  generate-sdks:
    name: Generate SDKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node dependencies
        run: npm install
      - name: Generate SDKs
        run: npm run generate
      - name: Save generated SDKs
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*
  run-php-tests:
    name: Run PHP tests
    needs: generate-sdks
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve generated SDKs
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: pcov
      - name: Install PHP dependencies
        working-directory: dist/sdk-php/
        run: composer install
      - name: Run tests
        working-directory: dist/sdk-php/
        run: bash run-tests.sh
  run-python-tests:
    name: Run Python tests
    needs: generate-sdks
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve generated SDKs
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install tox
        run: pip install tox
      - name: Run tests
        working-directory: dist/sdk-python/
        run: tox
